#166240819 email verification
andela/savage_rangers-ah pull request #27
Opened 2019-06-13 17:15 UTC by truestbyheart

#### What does this PR do?
 * Enable the user to verify email.
#### Description of Task to be completed?
 * After successful registration, an email is sent to the user's personal email provider.
 * Once the user receives the email with the verification link and clicks it, the user is redirected to the ``/auth/verifyEmail`` endpoint to verify the user.
#### How should this be manually tested?
* Clone the repo to  local machine.
* Run ``npm install``   to install the dependencies.
* Set up the   ``.env`` as instructed by the   ``.env-example``
* Run  ``npm  start``.
* Post registration data to  ``/api/auth/signup``   and check your email (check the spam).
*  Click the verification link.
#### What are the relevant pivotal tracker stories?
#[166240819](https://www.pivotaltracker.com/story/show/166240819)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2019-06-13 at 18 07 18" src="https://user-images.githubusercontent.com/37019531/59452872-fa356380-8e0e-11e9-9343-d00ccbc17f35.png">
<img width="1440" alt="Screen Shot 2019-06-13 at 19 04 11" src="https://user-images.githubusercontent.com/37019531/59452896-08837f80-8e0f-11e9-81c7-51d7a36010b9.png">
<img width="1440" alt="Screen Shot 2019-06-13 at 19 04 47" src="https://user-images.githubusercontent.com/37019531/59453023-4a142a80-8e0f-11e9-9986-2a5bed9471c8.png">

2019-06-13 18:01 UTC, nkpremices requested changes
@truestbyheart would you mind to add the documentation on your endpoint on the swaager.josn file?

2019-06-13 18:01 UTC, premlogic commented on package.json
> -    "babel-plugin-istanbul": "^5.1.2",
if the travis build can still passing after removing it it's alright. Otherwise, we will need to keep it. Let's wait for the travis build

2019-06-13 18:01 UTC, premlogic commented on src/helpers/Mailer/templates/notifications.js
> +  const link = generateLink(userData.link, {
Well guessed man. Now my test and yours can pass together...

2019-06-13 18:03 UTC, truestbyheart commented on package.json
> -    "babel-plugin-istanbul": "^5.1.2",
On it

2019-06-13 18:03 UTC, truestbyheart commented on src/helpers/Mailer/templates/notifications.js
> +  const link = generateLink(userData.link, {
Great

2019-06-14 09:25 UTC, nkpremices approved these changes
As tests are passing and the swagger documentation is added, I approve.

2019-06-17 17:06 UTC, murediane approved these changes
how does this generateToken work? and the test is failing. Otherwise, the rest looks good to me

2019-06-24 10:12 UTC, MCFrank16 commented
please resolve these conflicts and make the Travis pass for I to approve this PR

2019-06-24 19:50 UTC, closed without merging