#166647233 enable authors to delete their own articles
andela/savage_rangers-ah pull request #59
Opened 2019-07-01 11:29 UTC by Ramadhan0

### What does this PR do?
##### Delete article 

### Description of Task to be completed?
### [use case](https://docs.google.com/document/d/1lnqSEe9rLcqlBIPJStaoen5rY8AIjYfVQpAiL0gyMl4/edit?usp=sharing)
##### Have this point working 
* DELETE ```/api/articles/:slug```: this is the endpoint, Author will hit whenever he/she wants to delete his/her own articles
#### How should this be manually tested?
* Clone the repo by typing  ```git clone https://github.com/andela/savage_rangers-ah``` into the terminal

* Install development dependencies by type ```npm install```
* Run the server with this command ```npm run dev```
* Test it with your postman typing:
 
   ```localhost:3001/api/articles/:slug```

#### What are the relevant pivotal tracker stories?
[166647233](https://www.pivotaltracker.com/story/show/166647233)

2019-07-03 07:42 UTC, MCFrank16 approved these changes

2019-07-03 07:42 UTC, MCFrank16 commented on src/api/controllers/articleController.js
> + *
why did you remove this js doc comment, this will help anyone to understand what's going on down to the page he is on

2019-07-03 07:42 UTC, MCFrank16 commented on src/api/controllers/articleController.js
> +      status: res.statusCode,
where are you reading the statusCode from I saw that you changed it in the imported variable to status

2019-07-03 07:42 UTC, MCFrank16 commented on src/api/controllers/articleController.js
> +      status: res.statusCode,
so I don't think the status response will be available

2019-07-03 13:11 UTC, MemunaHaruna requested changes

2019-07-03 13:11 UTC, MemunaHaruna commented on README.md
> +- Clone the repo using:
@Ramadhan0 this file shouldn't be in your PR.

2019-07-03 13:11 UTC, MemunaHaruna commented on src/api/controllers/articleController.js
> +import status from '../../helpers/constants/status.codes';
@Ramadhan0 please leave it as `statusCodes`. No point changing it to `status`

2019-07-03 13:11 UTC, MemunaHaruna commented on src/api/controllers/articleController.js
> +const { CREATED } = status;
@Ramadhan0 why this change?

2019-07-03 13:11 UTC, MemunaHaruna commented on src/api/controllers/articleController.js
> +      tagList: updateContent.tagList,
@Ramadhan0 please rebase properly with develop.

2019-07-03 13:11 UTC, MemunaHaruna commented on src/api/models/article.js
> +        type: DataTypes.STRING,
@Ramadhan0 you don't need to make any changes to this file.

2019-07-04 11:35 UTC, MemunaHaruna approved these changes

2019-07-04 11:35 UTC, MemunaHaruna commented
@Ramadhan0 for future reference, please ensure your branch name adheres to our team conventions.

2019-07-04 11:38 UTC, merged