Ch deploy to heroku #166240813
andela/savage_rangers-ah pull request #6
Opened 2019-06-05 12:58 UTC by alainburindi

#### What does this PR do?
Deploy the base appplication to heroku
#### How should this be manually tested?
for development process access the endpoints using this link https://savage-rangers-ah-staging.herokuapp.com/
for deployment process use this link https://savage-rangers-ah.herokuapp.com/
#### What are the relevant pivotal tracker stories?
#166240813

2019-06-05 14:28 UTC, bdushimi commented
Please follow the PR naming convention:
#[STORY_ID] [Story description]

2019-06-05 14:30 UTC, bdushimi requested changes
Please follow the PR naming convention:
#[STORY_ID] [Story description]

2019-06-05 14:32 UTC, bdushimi commented
This link https://savage-rangers-ah.herokuapp.com/ is not up!

2019-06-05 15:00 UTC, alainburindi commented
> Please follow the PR naming convention:
> #[STORY_ID] [Story description]

done

2019-06-05 15:03 UTC, alainburindi commented
> This link https://savage-rangers-ah.herokuapp.com/ is not up!

It is waiting for the deployment process from Tarvis-ci

2019-06-05 18:26 UTC, truestbyheart reviewed
Can you remove the callback function on ```app.listen```

2019-06-06 06:53 UTC, bdushimi requested changes

2019-06-06 06:53 UTC, bdushimi commented on src/index.js
> +app.listen( port, () =>{});
Usually, you want to console/print a meaningful message in this callback function... something like " app listening on port ${port}!` "

2019-06-06 06:56 UTC, bdushimi commented
I do not see any configurations that have something to do with deploying the app on Heroku in this PR.

2019-06-06 08:46 UTC, merged

2019-06-06 08:58 UTC, bdushimi commented
Testing re-opening this PR