#167224203 get highlighted text
andela/savage_rangers-ah pull request #75
Opened 2019-07-11 13:51 UTC by alainburindi

##### What does this PR do?
Have the ```get highlighted text``` working

##### Description of Task to be completed?
* Allow user to get highlighted text
##### Have the following endpoints working  
* GET ```/api/articles/:slug/highlight```: highlight a text
##### How should this be manually tested?
* Clone the repos
* Install dependencies ```npm install```
* Run ```npm run dev```
* Get higlighted text in an article
##### What are the relevant pivotal tracker stories?
[#167224203](https://www.pivotaltracker.com/story/show/167224203)

2019-07-11 15:34 UTC, truestbyheart requested changes

2019-07-11 15:34 UTC, truestbyheart commented on src/api/controllers/articleController.js
> +<<<<<<< HEAD
Resolve this conflict

2019-07-15 16:40 UTC, truestbyheart approved these changes

2019-07-16 09:19 UTC, Ramadhan0 approved these changes

2019-07-16 09:19 UTC, Ramadhan0 commented on src/api/routes/articleRouter.js
> +
please remove these empty lines @alainburindi

2019-07-16 11:27 UTC, MemunaHaruna commented on src/helpers/constants/error.messages.js
> +  noHighlight: 'No highlited text for this article',
@alainburindi it's `highlighted` not `highlited`

This mistake is happening across several files so please correct in other places, as well.

2019-07-16 11:29 UTC, MemunaHaruna approved these changes

2019-07-16 13:49 UTC, merged